name: Deploy Demo to GitHub Pages

on:
  push:
    branches: ["master"]
  pull_request: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build:gh-pages

      # add 404.html for SPA fallback
      - run: cp gh-pages/index.html gh-pages/404.html
      - run: touch gh-pages/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./gh-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
